export interface CuisineCategory {
  category: string
  items: string[]
}

export const CUISINE_CATEGORIES: CuisineCategory[] = [
  {
    category: 'Swallow',
    items: [
      'Amala (Yam Flour)',
      'Amala (Plantain Flour)',
      'Eba (Garri)',
      'Semovita',
      'Wheat',
      'Pounded Yam',
      'Fufu (Cassava)',
      'Tuwo Shinkafa',
      'Tuwo Masara',
      'Starch (Usi)',
      'Lafun',
      'Akpu',
      'Semo',
      'Plantain Fufu (Loi Loi)',
      'Cassava Flakes Swallow',
      'Ekuru',
      'Agidi (Eko)',
      'Poundo Yam (Instant Flour)',
      'Oat Swallow',
      'Semo & Oat Mix',
      'Wheat & Semo Mix',
      'Plantain & Cassava Swallow',
    ],
  },
  {
    category: 'Soups',
    items: [
      'Egusi Soup',
      'Okra Soup (Ila Asepo)',
      'Draw Soup (Okra & Ogbono)',
      'Ogbono Soup',
      'Efo Riro',
      'Afang Soup',
      'Edikang Ikong',
      'Banga Soup (Ofe Akwu)',
      'Oha Soup',
      'Ofe Onugbu (Bitterleaf Soup)',
      'Ofe Owerri',
      'Nsala Soup (White Soup)',
      'Miyan Gyada (Groundnut Soup)',
      'Miyan Kuka',
      'Miyan Taushe',
      'Ewedu Soup',
      'Gbegiri',
      'Uziza Soup',
      'Ukwa (Breadfruit Porridge)',
      'Atama Soup',
      'Editan Soup',
      'Owo Soup',
      'Fisherman Soup',
      'Vegetable Soup (Mixed Greens)',
      'Ogiri Soup',
      'Cray Fish Soup',
    ],
  },
  {
    category: 'Stews',
    items: [
      'Tomato Stew (Obe Ata)',
      'Ayamase (Ofada Stew)',
      'Ofe Akwu (Palm Nut Stew)',
      'Buka Stew',
      'Green Pepper Stew (Efo Elegusi Stew)',
      'Red Stew (Obe Din-Din)',
      'Dry Pepper Stew (Ata Gbigbe)',
      'Fish Stew',
      'Chicken Stew',
      'Beef Stew',
      'Mixed Meat Stew',
      'Curry & Thyme Stew',
      'Coconut Stew',
      'Efo Stew (Spinach Stew)',
    ],
  },
  {
    category: 'Rice',
    items: [
      'Jollof Rice',
      'Nigerian Fried Rice',
      'Chinese Fried Rice',
      'Coconut Rice',
      'Native Rice',
      'Ofada Rice & Ayamase',
      'Palm Oil Rice',
      'White Rice & Stew',
      'Rice & Beans',
      'Concoction Rice',
      'Corn & Rice Porridge',
      'Rice & Vegetable Sauce',
      'Ogbono Rice',
      'Curry Rice',
      'Yellow Rice (Turmeric)',
      'Coconut Jollof Rice',
      'Party Jollof Rice',
      'Rice & Fish Stew',
    ],
  },
  {
    category: 'Pasta & Noodles',
    items: [
      'Jollof Spaghetti',
      'Fried Spaghetti',
      'Stir Fry Noodles',
      'Singapore Noodles',
      'Indomie Stir Fry',
      'Macaroni Jollof',
      'Spaghetti Bolognese',
      'Chow Mein',
      'Egg Noodles',
      'Creamy Pasta',
      'Vegetable Pasta',
      'Seafood Noodles',
    ],
  },
  {
    category: 'Proteins & Grills',
    items: [
      'Suya',
      'Asun (Spicy Goat Meat)',
      'Peppered Chicken',
      'Peppered Snail',
      'Peppered Turkey',
      'Grilled Fish (Point & Kill)',
      'Grilled Chicken',
      'Grilled Turkey',
      'Barbecue Chicken',
      'Kilishi',
      'Balangu',
      'Nkwobi',
      'Isi Ewu',
      'Ponmo',
      'Fried Fish',
      'Fried Chicken',
      'Fried Turkey',
      'Boiled Chicken',
      'Boiled Turkey',
      'Grilled Prawns',
      'Peppered Beef',
      'Gizdodo (Gizzard & Plantain)',
      'Grilled Croaker Fish',
    ],
  },
  {
    category: 'Peppersoup',
    items: [
      'Catfish Pepper Soup',
      'Goat Meat Pepper Soup',
      'Cow Leg Pepper Soup',
      'Chicken Pepper Soup',
      'Assorted Meat Pepper Soup',
      'Fish Pepper Soup',
      'Snail Pepper Soup',
      'Turkey Pepper Soup',
      'Panla Fish Pepper Soup',
    ],
  },
  {
    category: 'Small Chops & Snacks',
    items: [
      'Puff Puff',
      'Chin Chin',
      'Meat Pie',
      'Fish Pie',
      'Sausage Roll',
      'Egg Roll',
      'Spring Roll',
      'Samosa',
      'Buns',
      'Doughnut',
      'Akara',
      'Moi Moi',
      'Plantain Chips (Ipekere)',
      'Coconut Chips',
      'Kuli Kuli',
      'Peanut Brittle (Robo)',
      'Boli (Roasted Plantain)',
      'Roasted Corn & Pear',
      'Suya Rolls',
      'Chicken Skewers',
      'Fish Rolls',
      'Popcorn Chicken',
      'Yam Balls',
    ],
  },
  {
    category: 'Breakfast',
    items: [
      'Akara & Pap',
      'Moi Moi & Bread',
      'Yam & Egg Sauce',
      'Plantain & Egg Sauce',
      'Bread & Akamu (Custard)',
      'Custard',
      'Sausage & Egg',
      'Ewa Agoyin (Beans & Sauce)',
      'Bread & Beans',
      'Indomie & Egg',
      'Sweet Potato Porridge',
    ],
  },
  {
    category: 'Porridge',
    items: [
      'Yam Porridge (Asaro)',
      'Unripe Plantain Porridge',
      'Potato Porridge',
      'Beans Porridge (Ewa Riro)',
      'Vegetable Porridge',
      'Cocoyam Porridge',
      'Ukwa Porridge',
      'Corn Porridge',
    ],
  },
  {
    category: 'Local Drinks',
    items: [
      'Zobo',
      'Chapman',
      'Kunu Aya (Tiger Nut Drink)',
      'Kunu Gyada',
      'Fura da Nono',
      'Palm Wine',
      'Ginger Drink',
      'Tamarind Drink',
      'Pineapple Ginger Juice',
      'Bissap',
    ],
  },
  {
    category: 'Pastries & Baking',
    items: [
      'Meat Pie',
      'Fish Pie',
      'Sausage Roll',
      'Scotch Eggs',
      'Chocolate Cake',
      'Red Velvet Cake',
      'Vanilla Cake',
      'Carrot Cake',
      'Banana Bread',
      'Coconut Bread',
      'Cupcakes',
      'Cinnamon Rolls',
      'Croissants',
      'Danish Pastry',
      'Shortbread Cookies',
      'Chocolate Chip Cookies',
      'Pancakes',
      'Waffles',
      'Chin Chin (Baked)',
      'Puff Puff (Baked Variant)',
    ],
  },
  {
    category: 'Desserts & Sweets',
    items: [
      'Coconut Candy',
      'Plantain Pudding',
      'Tapioca Pudding',
      'Cassava Pudding',
      'Coconut Rice Pudding',
      'Zobo Jelly',
      'Fruit Parfait',
      'Yogurt Parfait',
      'Granola Parfait',
      'Chocolate Mousse',
      'Trifle',
      'Ice Cream',
      'Milkshake',
      'Fruit Salad',
      'Banana Split',
    ],
  },
  {
    category: 'Yoruba Specialties',
    items: [
      'Amala & Ewedu-Gbegiri',
      'Ofada Rice & Ayamase',
      'Ekuru',
      'Iyan (Pounded Yam)',
      'Efo Riro',
      'Gbegiri',
      'Dodo (Fried Plantain)',
      'Ewa Agoyin',
      'Ata Dindin (Fried Pepper Sauce)',
    ],
  },
  {
    category: 'Igbo Specialties',
    items: [
      'Ofe Onugbu',
      'Ofe Owerri',
      'Nkwobi',
      'Isi Ewu',
      'Abacha (African Salad)',
      'Ukwa',
      'Oha Soup',
      'Nsala Soup',
      'Fufu & Onugbu',
    ],
  },
  {
    category: 'Hausa & Northern Specialties',
    items: [
      'Tuwo Shinkafa',
      'Tuwo Masara',
      'Miyan Kuka',
      'Miyan Taushe',
      'Fura da Nono',
      'Kilishi',
      'Suya',
      'Dan Wake',
      'Masa (Rice Cake)',
      'Kunu',
      'Alale',
      'Miyan Zogale (Moringa Soup)',
    ],
  },
  {
    category: 'South-South Specialties',
    items: [
      'Afang Soup',
      'Edikang Ikong',
      'Ekpang Nkukwo',
      'Atama Soup',
      'Editan Soup',
      'Abak Iyak',
      'Banga Soup',
      'Starch & Banga',
      'Kekefiya',
      'Fisherman Soup',
      'Bole & Fish',
    ],
  },
  {
    category: 'Continental & Fusion',
    items: [
      'Shawarma',
      'Grilled Salad',
      'Chicken Alfredo',
      'BBQ Ribs',
      'Fried Rice with Sausage',
      'Club Sandwich',
      'Chicken Wrap',
      'Beef Burger',
      'Vegetable Stir Fry',
    ],
  },
]

export const CUISINE_SELECTION_LIMIT = 6
