// Lightweight mock data for pages that expect demo chefs/locations.
// This file will be deleted once the Supabase schema is applied and
// all routes are wired to real data (Milestone 0, Phase 0.1).

export const MOCK_CHEFS: any[] = [
  {
    id: 'demo-1',
    full_name: 'Chioma Okafor',
    name: 'Chioma',
    nickname: 'Chioma',
    tagline: 'Smoky jollof & proper stew',
    role: 'cook',
    looking_for: 'Food dates and loyal customers',
    age: 26,
    avatar_url:
      'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1200&q=80',
    bio: "If you love smoky jollof, soft plantain, and proper stew… you're in the right place.",
    cuisines: ['Nigerian'],
    interests: ['Home cooking', 'Spicy', 'Street food'],
    favorite_foods: ['Jollof Rice', 'Fried Plantain', 'Chicken'],
    photos: [],
    specialty: 'Jollof Rice',
    price_min: 2500,
    price_max: 7000,
    rating: 4.9,
    review_count: 47,
    is_bot: false,
    is_verified: true,
    kyc_status: 'verified',
    location: 'Surulere, Lagos',
    lat: 6.4541,
    lng: 3.3947,
    emoji: '🍛',
    daily_special: {
      id: 'ds-1',
      cook_id: 'demo-1',
      title: 'Ofe Akwu + Pounded Yam',
      price: 5500,
      available_until: new Date(Date.now() + 6 * 3600000).toISOString(),
      created_at: new Date().toISOString(),
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-2',
    full_name: 'Tunde Adeyemi',
    name: 'Tunde',
    nickname: 'Tunde',
    tagline: 'Late-night suya & cold drinks',
    role: 'cook',
    looking_for: 'Late-night suya and good vibes',
    age: 29,
    avatar_url:
      'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&w=1200&q=80',
    bio: 'Proper suya, hot yaji, and cold drinks. Come chop.',
    cuisines: ['Nigerian'],
    interests: ['Street food', 'BBQ', 'Spicy'],
    favorite_foods: ['Suya', 'Peppered Snail', 'Asun'],
    photos: [],
    specialty: 'Suya',
    price_min: 2000,
    price_max: 6000,
    rating: 4.7,
    review_count: 31,
    is_bot: false,
    is_verified: true,
    kyc_status: 'verified',
    location: 'Ikeja, Lagos',
    lat: 6.46,
    lng: 3.41,
    emoji: '🍢',
    daily_special: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-3',
    full_name: 'Fatima Bello',
    name: 'Fatima',
    nickname: 'Fatima',
    tagline: 'Northern soups & tuwo sinafi',
    role: 'cook',
    looking_for: 'Regulars who appreciate Northern cuisine',
    age: 31,
    avatar_url:
      'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=1200&q=80',
    bio: 'Miyan kuka, tuwo sinafi, pepper soup. Come eat like a northerner.',
    cuisines: ['Northern Nigerian', 'Hausa'],
    interests: ['Traditional cooking', 'Spices', 'Soups'],
    favorite_foods: ['Miyan Kuka', 'Tuwo Shinkafa', 'Masa'],
    photos: [],
    specialty: 'Miyan Kuka',
    price_min: 3000,
    price_max: 8000,
    rating: 4.8,
    review_count: 22,
    is_bot: false,
    is_verified: true,
    kyc_status: 'verified',
    location: 'Gbagada, Lagos',
    lat: 6.55,
    lng: 3.38,
    emoji: '🥘',
    daily_special: {
      id: 'ds-3',
      cook_id: 'demo-3',
      title: 'Miyan Kuka + Tuwo Shinkafa',
      price: 4500,
      available_until: new Date(Date.now() + 4 * 3600000).toISOString(),
      created_at: new Date().toISOString(),
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const MOCK_MAP_LOCATIONS: any[] = MOCK_CHEFS.map((c) => ({
  id: c.id,
  lat: c.lat,
  lng: c.lng,
  name: c.full_name ?? c.name ?? c.nickname,
  cuisine: c.cuisines?.[0] ?? 'Nigerian',
  price: c.price_min,
  emoji: c.emoji ?? '🍽️',
}))
